### ISSUE TITLE
XML file does not appear to have any style information...

### ISSUE THREAD

**Issue by WillMarchant** [OpenC3/openc3.com#17] opened 2022-11-14 16:12 UTC
This is on a RHEL 7 system.  I followed the install instructions at https://openc3.com/docs/v5/installation and the "./openc3 start" seems to have run.  But after launching "firefox http://localhost:2900" the web browser complains about the resulting web page as seen here:  
<img width="1114" alt="Screen Shot 2022-11-14 at 10 56 50 AM" src="https://user-images.githubusercontent.com/20227115/201706429-4c7fbb9b-bc26-4d98-ae49-f984dcf421d4.png">

Here is what openc3 says with no options and also the versions of docker and docker-compose:

-bash-4.2$ ./openc3.sh
Usage: ./openc3.sh [cli, cliroot, start, stop, cleanup, build, deploy]
*  cli: run a cli command as the default user ('cli help' for more info)
*  cliroot: run a cli command as the root user ('cli help' for more info)
*  start: start the docker-compose openc3
*  stop: stop the running dockers for openc3
*  cleanup: cleanup network and volumes for openc3
*  run: run the prebuilt containers for openc3
*  util: various helper commands
*    encode: encode a string to base64
*    hash: hash a string using SHA-256
*    save: save images to tar files
*    load: load images to tar files
*    clean: remove node_modules, coverage, etc
*    hostsetup: setup host for redis

-bash-4.2$ docker --version
Docker version 20.10.7, build f0df350
-bash-4.2$ docker-compose --version
Docker Compose version v2.12.2
-bash-4.2$

I have the "./openc3 start" messages saved but it's almost a MB and wouldn't upload here...

**Comment by jmthomas** [comment] 2022-11-23 21:55
Not related to website and duplicate of https://github.com/OpenC3/cosmos/issues/245

**Closed by jmthomas** 2022-11-23 21:55 UTC
